--- #YAML:1.0
name:                TL1ng
version:             0.08
abstract:            A simple, flexible, OO way to work with TL1.
license:             perl
author:              
    - Steve Scaffidi <sscaffidi@cpan.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Net::Telnet:                   3.03
    Time::Local:                   1.17
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
